#!/bin/sh

# Script for running miniJava compiler tests. (Jingke Li) 
#
# Usage:
#   run tst/test01.java      -- test a single program 
#   run tst/test*.java       -- test all programs
#
# The script will show diffs between the compiler's output and the
# reference version. If it runs in silence, it means a perfect match.
#
for i
do
	d=`dirname $i`
	f=`basename $i .ir`
	echo $d/$f:
#	java IRGen  $d/$f.ast 1> $d/$f.ir || continue 1
#	if [ -r $d/$f.ir.ref ]; then diff -w $d/$f.ir.ref $d/$f.ir; else cp $d/$f.ir $d/$f.ir.ref; fi
	java -ea X86Gen $d/$f.ir 1> $d/$f.s || continue 1
	if [ -r $d/$f.s.ref ]; then diff -w $d/$f.s.ref $d/$f.s; else cp $d/$f.s $d/$f.s.ref; fi
	gcc -Wl,-no_pie -o $d/$f $d/$f.s lib.c
	$d/$f > $d/$f.out
	if [ -r $d/$f.out.ref ]; then diff $d/$f.out.ref $d/$f.out; else cp $d/$f.out $d/$f.out.ref; fi
done
exit 0

